# Generated by Django 5.1 on 2024-09-07 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='Membership_model',
        ),
    ]
