# Generated by Django 5.0 on 2024-09-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_membership_model_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Job_title', models.CharField(max_length=100)),
            ],
        ),
    ]
